// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FooterInfoController from "./footer_info_controller.jsx"
application.register("footer-info", FooterInfoController)

import HeightController from "./height_controller.js"
application.register("height", HeightController)

import ViewController from "./view_controller.js"
application.register("view", ViewController)
