default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DEV_DATABASE_URL", nil) %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", nil) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>

test:
  <<: *default
  url: <%= ENV.fetch("TEST_DATABASE_URL", nil) %>
